name: (one-off) Generate APT signing key

on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GPG key
        run: |
          mkdir -p /tmp/gnupg-gen
          export GNUPGHOME=/tmp/gnupg-gen
          cat > keyspec <<EOF
          %no-protection
          Key-Type: RSA
          Key-Length: 4096
          Name-Real: Minimal Clock APT Repo
          Name-Email: apt@ivaan.cc
          Expire-Date: 0
          %commit
          EOF
          gpg --batch --gen-key keyspec
          gpg --armor --export-secret-keys > private.asc
          gpg --armor --export > public.asc

      - uses: actions/upload-artifact@v4
        with:
          name: apt-gpg-keys
          path: |
            private.asc
            public.asc
